# Generated by Django 4.0.3 on 2022-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
